books/urls.py
from django.conf.urls import url
from . import views, models

app_name = 'books'
urlpatterns = [   
    url(r'^$', views.hello),
    url(r'^time/$', views.current_datetime),
    url(r'^time/plus/(\d{1,2})/$', views.hours_ahead),
    url(r'^meta/$', views.display_meta),
    # url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search, {'model': models.Book}),
    url(r'^contact/$', views.contact),
]

family/urls.py
from django.conf.urls import url
from . import views

app_name = 'family'
urlpatterns = [
    url(r'^$', views.Index, name='index'),

    url(r'^member/myMemberList/$', views.MyMemberList, name='my_member'),
    url(r'^member/memberListOfFamily/(?P<family_id>[0-9]+)/$', views.FamilyMemberList, name='member_list'),
    url(r'^member/createMember/$', views.CreateMember, name='create_member'),
    url(r'^member/(?P<member_id>[0-9]+)/$', views.ModifyMember, name='modify_member'),

    url(r'^family/myFamilyList/$', views.FamilyList, name='family_list'),
    url(r'^family/(?P<family_id>[0-9]+)/$', views.FamilyDetails, name='family_details'),
    url(r'^family/createFamilyByMember/(?P<member_id>[0-9]+)/$', views.CreateFamily, name='create_family'),

    url(r'^relationship/member/(?P<member_id>[0-9]+)/chooseFamily/$', views.ChooseFamily, name='choose_family'),
    url(r'^relationship/member/(?P<member_id>[0-9]+)/joinFamily/(?P<family_id>[0-9]+)/$', views.JoinInFamily, name='join_family'),
    url(r'^relationship/genealogyOfFamily/(?P<family_id>[0-9]+)/$', views.FamilyRelationship, name='relationship'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^accounts/login/$',  login),
    url(r'^accounts/logout/$', logout),
    url(r'^accounts/profile/$', views.profile),
    url(r'^accounts/register/$', views.register),
    url(r'', include('family.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

family/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

def individual_directory_path(instance, filename):
    return 'individual_{0}/{1}'.format(instance.date_of_birth, filename)

class Individual(models.Model):
    GENDER = [
        ('F', 'Female'),
        ('M', 'Male'),
    ]
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10, choices=GENDER)
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=50)
    other_individual_details = models.TextField(null=True, blank=True)
    image_path = models.FileField(upload_to=individual_directory_path, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date_of_birth']

    def natural_key(self):
        return { 'last_name': self.last_name , 'image_path': u'%s' %(self.image_path) }

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

def family_directory_path(instance, filename):
    return 'family_{0}/{1}'.format(instance.user.id, filename)

class Family(models.Model):
    head_of_family_individual_id = models.ForeignKey(Individual, on_delete=models.CASCADE)
    family_name = models.CharField(max_length=50)
    family_description = models.CharField(max_length=100, null=True, blank=True)
    family_date_from = models.DateField(null=True, blank=True)
    family_date_to = models.DateField(null=True, blank=True)
    other_family_details = models.TextField(null=True, blank=True)
    image_path = models.FileField(upload_to=family_directory_path, null=True, blank=True)
    is_public = models.BooleanField(default=False)

    def __unicode__(self):
        return self.family_name

class Relationship_Type(models.Model):
    TYPE = [
        ('C', 'Consanguinity'),
        ('M', 'Marriage'),
    ]
    relationship_type_code = models.CharField(primary_key=True, max_length=10, choices=TYPE)
    relationship_type_description = models.CharField(max_length=50)

    def __unicode__(self):
        return self.relationship_type_description

class Role(models.Model):
    ROLES = [
        ('F', 'Father'),
        ('M', 'Mother'),
        ('S', 'Son'),
        ('D', 'Daughter'),
        ('H', 'Husband'),
        ('W', 'Wife'),
    ]
    role_code = models.CharField(primary_key=True, max_length=10, choices=ROLES)
    role_description = models.CharField(max_length=50)

    def __unicode__(self):
        return self.role_description

class Relationship(models.Model):
    family_id = models.ForeignKey(Family, on_delete=models.CASCADE)
    individual_1_id = models.ForeignKey(Individual, related_name='individual_1', on_delete=models.CASCADE)
    individual_2_id = models.ForeignKey(Individual, related_name='individual_2', on_delete=models.CASCADE)
    relationship_type_code = models.ForeignKey(Relationship_Type, on_delete=models.CASCADE)
    individual_1_role_code = models.ForeignKey(Role, related_name='individual_1_role', on_delete=models.CASCADE)
    individual_2_role_code = models.ForeignKey(Role, related_name='individual_2_role', on_delete=models.CASCADE)
    date_relationship_started = models.DateField()
    date_relationship_ended = models.DateField(null=True, blank=True)
    relationship_place = models.CharField(max_length=50, null=True, blank=True)
    other_relationship_details = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['date_relationship_started']

family/forms.py
from django.forms import ModelForm
from .models import Individual, Family, Relationship

class MemberForm(ModelForm):
    class Meta:
        model = Individual
        fields = ['first_name', 'last_name', 'gender', 'date_of_birth', 'place_of_birth', 'other_individual_details', 'image_path']
        localized_fields = ('date_of_birth',)

class FamilyForm(ModelForm):
    class Meta:
        model = Family
        fields = ['family_name', 'family_description', 'family_date_from', 'family_date_to','other_family_details', 'image_path']
        localized_fields = ('family_date_from', 'family_date_to')

class RelationshipForm(ModelForm):
    class Meta:
        model = Relationship
        fields = ['individual_2_id', 'individual_2_role_code', 'date_relationship_started', 'date_relationship_ended', 'relationship_place', 'other_relationship_details']
        localized_fields = ('date_relationship_started', 'date_relationship_ended')

family/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from django.db.models import Q
from .models import Individual, Family, Relationship, Role, Relationship_Type
from .forms import MemberForm, FamilyForm, RelationshipForm


def Index(request):
    return render(request, 'family/index.html')

# Member
@login_required
def CreateMember(request):
    if request.method == 'POST':
        form = MemberForm(request.POST, request.FILES)
        if form.is_valid():
            new_member = form.save(commit=False)
            new_member.created_by = request.user
            new_member.save()
            return redirect('family:my_member')
    else:
        form = MemberForm()
    return render(request, 'family/member_form.html', {'form': form})

@login_required
def ModifyMember(request, member_id):
    instance = Individual.objects.get(pk=member_id)
    if request.method == 'POST':
        form = MemberForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('family:my_member')
    else:
        form = MemberForm(instance=instance)
    return render(request, 'family/member_form.html', {'form': form, 'member': instance})

@login_required
def MyMemberList(request):
    members = Individual.objects.filter(created_by=request.user).exclude(family__isnull=False).exclude(individual_1__isnull=False)
    return render(request, 'family/member_list.html', {'members': members})

def FamilyMemberList(request, family_id):
    family = Family.objects.get(pk=family_id)
    head_member = Individual.objects.filter(family__id=family_id)
    other_members = Individual.objects.filter(individual_1__family_id=family_id)
    members = head_member | other_members
    return render(request, 'family/member_list.html', {'members': members, 'family': family})

# Family
@login_required
def CreateFamily(request, member_id):
    try:
        family = Family.objects.get(head_of_family_individual_id=member_id)
    except (KeyError, Family.DoesNotExist):
        member = Individual.objects.get(pk=member_id)
        if request.method == 'POST':
            form = FamilyForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.head_of_family_individual_id = member
                instance.save()
                return redirect('family:family_list')
        else:
            form = FamilyForm()
        return render(request, 'family/family_form.html', {'form': form, 'member': member})
    else:
        return redirect('family:family_details', family_id=family.id)

def FamilyDetails(request, family_id):
    instance = Family.objects.get(pk=family_id)
    member = instance.head_of_family_individual_id
    if request.method == 'POST':
        form = FamilyForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('family:family_list')
    else:
        form = FamilyForm(instance=instance)
    return render(request, 'family/family_form.html', {'form': form, 'member': member, 'family': instance})

@login_required
def FamilyList(request):
    families = Family.objects.filter(head_of_family_individual_id__created_by=request.user)
    return render(request, 'family/family_list.html', {'families': families})

# Relationship
@login_required
def ChooseFamily(request, member_id):
    member = Individual.objects.get(pk=member_id)
    families = Family.objects.exclude(relationship__individual_1_id=member_id).exclude(head_of_family_individual_id=member_id)
    return render(request, 'family/relationship_choose_family.html', {'member': member, 'families': families})

@login_required
def JoinInFamily(request, member_id, family_id):
    member = Individual.objects.get(pk=member_id)
    family = Family.objects.get(pk=family_id)
    
    head_member = Individual.objects.filter(family__id=family_id)
    other_members = Individual.objects.filter(individual_1__family_id=family_id, individual_1__relationship_type_code='C')
    members = head_member | other_members

    roles2 = Role.objects.filter(Q(role_code='F') | Q(role_code='M') | Q(role_code='H') | Q(role_code='W'))

    if request.method == 'POST':
        form = RelationshipForm(request.POST)
        if form.is_valid():
            relation = form.save(commit=False)
            relation.family_id = family
            relation.individual_1_id = member

            role2 = relation.individual_2_role_code.role_code

            if role2 == 'F' or role2 == 'M':
                type_code = 'C'
            else:
                type_code = 'M'
            if type_code == 'C':
                if member.gender == 'M':
                    role_code = 'S'
                else: 
                    role_code = 'D'
            else:
                if member.gender == 'M':
                    role_code = 'H'
                else: 
                    role_code = 'W'

            relation.relationship_type_code = Relationship_Type.objects.get(relationship_type_code=type_code)
            relation.individual_1_role_code = Role.objects.get(role_code=role_code)
            relation.save()
            return redirect('family:my_member')
    else:
        form = RelationshipForm()
    return render(request, 'family/relationship_form.html', {'form': form, 'member': member, 'family': family, 'members': members, 'roles': roles2})

def FamilyRelationship(request, family_id):
    head_member = family = Family.objects.get(pk=family_id).head_of_family_individual_id
    relations = Relationship.objects.filter(family_id=family_id)
    return render(request, 'family/relationship_genealogy.html', {'head_member': head_member, 'relations': relations})

family/templates/family/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'libs/css/weui.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'family/css/style.css' %}"> -->
  <style type="text/css">
    header {
      padding: 20px 20px 10px;
      -webkit-box-align: center;
      -webkit-align-items: center;
      align-items: center;
      -webkit-transition: .3s;
      transition: .3s;
      background: #fff;
    }
    .logo {
      display: block;
      width: 137px;
      height: 32px;
      background-image: url({% static 'family/images/Familytree.png' %});
      background-size: 100%;
    }
  </style>
  {% block style %}{% endblock %}
</head>
<body>  
  <header class="weui-flex">
    <a href="{% url 'family:index' %}" class="weui-flex__item"><i class="logo"></i></a>
    {% if user.is_authenticated %}
    <a href="/accounts/profile" class="weui-btn weui-btn_mini weui-btn_plain-primary">{{user.username}}</a>    
    {% else %}
    <a href="/accounts/login" class="weui-btn weui-btn_mini weui-btn_plain-primary">登录</a>
    {% endif %}
  </header>
  {% block content %}{% endblock %}
  {% block footer %}{% endblock %}
  {% block script %}{% endblock %}
</body>
</html>

family/templates/family/family_form.html
{% extends "family/base.html" %}

{% block title %}编辑家族信息{% endblock %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__bd">        
    <form  action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="weui-cells__title">编辑家族信息
      {% if family %}
        | <a href="{% url 'family:member_list' family.id %}">家族成员</a>
      {% endif %}
      </div>
      <div class="weui-cells weui-cells_form">
        <div class="weui-cell">
          <div class="weui-cell__hd"><label class="weui-label">创始人</label></div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="text" value="{{member}}" disabled>
          </div>
        </div>
        <div class="weui-cell {% if form.family_name.errors %}weui-cell_warn{% endif %}">      
          <div class="weui-cell__hd"><label class="weui-label">家族名称</label></div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="text" placeholder="请输入家族名称(必填)" name="family_name" value="{{form.family_name.value|default:''}}">
          </div>
          <div class="weui-cell__ft">
            <i class="weui-icon-warn"></i>
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd"><label class="weui-label">家族族语</label></div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="text" placeholder="请输入家族族语" name="family_description" value="{{form.family_description.value|default:''}}">
          </div>
          <div class="weui-cell__ft">
            <i class="weui-icon-warn"></i>
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd"><label for="" class="weui-label">创建日期</label></div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="date" value="{{form.family_date_from.value|date:'Y-m-d'}}" name="family_date_from">
          </div>
          <div class="weui-cell__ft">
            <i class="weui-icon-warn"></i>
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd"><label for="" class="weui-label">结束日期</label></div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="date" value="{{form.family_date_to.value|date:'Y-m-d'}}" name="family_date_to">
          </div>
          <div class="weui-cell__ft">
            <i class="weui-icon-warn"></i>
          </div>
        </div>      
        <div class="weui-cell">
          <div class="weui-cell__bd">
            <textarea class="weui-textarea" placeholder="详情介绍" rows="3" name="other_family_details">{{form.other_family_details.value|default:''}}</textarea>
            <div class="weui-textarea-counter"><span>0</span>/200</div>
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__bd">
            <div class="weui-uploader">
              <div class="weui-uploader__hd">
                <p class="weui-uploader__title">请上传族徽</p>
                <div class="weui-uploader__info"></div>
              </div>
              <div class="weui-uploader__bd">
                <ul class="weui-uploader__files" id="uploaderFiles">
                  {% if form.image_path.value %}
                  <li class="weui-uploader__file" style="background-image:url({{ MEDIA_URL }}{{ form.image_path.value }})"></li>
                  {% endif %}
                </ul>
                <div class="weui-uploader__input-box">
                  <input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" name="image_path">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="weui-cells__tips">{{ form.non_field_errors }}</div>
      <div class="weui-btn-area">
        <input class="weui-btn weui-btn_block weui-btn_primary" type="submit" value="保存">
      </div>      
    </form>    
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  var tmpl = '<li class="weui-uploader__file" style="background-image:url(#url#)"></li>',
    $uploaderInput = document.querySelector("#uploaderInput"),
    $uploaderFiles = document.querySelector("#uploaderFiles");

  $uploaderInput.onchange = function(e){
    var src, url = window.URL || window.webkitURL || window.mozURL, files = e.target.files;
    for (var i = 0, len = files.length; i < len; ++i) {
      var file = files[i];
      if (url) {
          src = url.createObjectURL(file);
      } else {
          src = e.target.result;
      }
      $uploaderFiles.innerHTML = tmpl.replace('#url#', src);
    }
  };
</script>
{% endblock %}

family/templates/family/family_list.html
{% extends "family/base.html" %}

{% block title %}家族列表{% endblock %}

{% block content %}
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">家族列表</div>
  <div class="weui-panel__bd">
    {% for family in families %}
    <a href="{% url 'family:family_details' family.id %}" class="weui-media-box weui-media-box_appmsg">
      <div class="weui-media-box__hd">
          <img class="weui-media-box__thumb" src="{{ MEDIA_URL }}{{ family.image_path }}" alt="">
      </div>
      <div class="weui-media-box__bd">
          <h4 class="weui-media-box__title">{{family.family_name}}</h4>
          <p class="weui-media-box__desc">{{family.other_family_details}}</p>
      </div>
    </a>
    {% endfor %}
  </div>  
  <div class="weui-panel__ft">
    <a href="javascript:void(0);" class="weui-cell weui-cell_access weui-cell_link">
      <div class="weui-cell__bd">查看更多</div>
      <span class="weui-cell__ft"></span>
    </a>    
  </div>
</div>
{% endblock %}

family/templates/family/index.html
{% extends "family/base.html" %}
{% load static %}

{% block title %}首页{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'libs/css/swiper.css' %}">
<style>
  .swiper-container {
    height: 200px;
  }
  .banner-image {
    width: 100%;
    height: 100%;
  }
  footer {
    padding-top: 40px;
    padding-bottom: 10px;
    padding-bottom: calc(10px + constant(safe-area-inset-bottom));
    padding-bottom: calc(10px + env(safe-area-inset-bottom));
    text-align: center;   
  }
</style>
{% endblock %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__hd">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <img src="{% static 'family/images/banner/banner_1.jpg' %}" alt="" class="banner-image">
        </div>
        <div class="swiper-slide">
          <img src="{% static 'family/images/banner/banner_2.jpg' %}" alt="" class="banner-image">
        </div>
        <div class="swiper-slide">
          <img src="{% static 'family/images/banner/banner_3.jpg' %}" alt="" class="banner-image">
        </div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
  <div class="weui-panel__bd">
    <div class="weui-grids">
      <a href="" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_clan.png' %}" alt="">
        </div>
        <p class="weui-grid__label">宗族起源</p>
      </a>      
      <a href="javascript:;" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_tabbar.png' %}" alt="">
        </div>
        <p class="weui-grid__label">姓氏由来</p>
      </a>
      <a href="" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_ genealogical.png' %}" alt="">
        </div>
        <p class="weui-grid__label">宗族族谱</p>
      </a>
      <a href="{% url 'family:family_list' %}" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_family.png' %}" alt="">
        </div>
        <p class="weui-grid__label">我的家族</p>
      </a>
      <a href="javascript:;" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_fund.png' %}" alt="">
        </div>
        <p class="weui-grid__label">家族信托</p>
      </a>
      <a href="javascript:;" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_legend.png' %}" alt="">
        </div>
        <p class="weui-grid__label">传奇人物</p>
      </a>      
      <a href="{% url 'family:my_member' %}" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_members.png' %}" alt="">
        </div>
        <p class="weui-grid__label">我的成员</p>
      </a>
      <a href="{% url 'family:create_member' %}" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_add_member.png' %}" alt="">
        </div>
        <p class="weui-grid__label">录入成员</p>
      </a>
      <a href="javascript:;" class="weui-grid">
        <div class="weui-grid__icon">
          <img src="{% static 'family/images/icon/icon_tabbar.png' %}" alt="">
        </div>
        <p class="weui-grid__label">Grid</p>
      </a>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
<footer>
  <div class="weui-footer">
    <p class="weui-footer__text">Copyright © 2018-2023 YRCH</p>
  </div>
</footer>
{% endblock %}

{% block script %}
<script src="{% static 'libs/js/swiper.js' %}"></script>
<script>
  var mySwiper = new Swiper ('.swiper-container', {
    pagination: {
      el: '.swiper-pagination',
    },
    autoplay: {
      delay: 5000,
    },
  })
</script>
{% endblock %}

family/templates/family/member_list.html
{% extends "family/base.html" %}
{% load static %}

{% block title %}成员列表{% endblock %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__hd">成员列表
    {% if family %}
     | <a href="{% url 'family:relationship' family.id %}">查看族谱</a>
    {% else %}
     | <a href="{% url 'family:create_member' %}">添加成员</a>
    {% endif %}
  </div>
  <div class="weui-panel__bd">
    <div class="weui-search-bar" id="searchBar">
      <form class="weui-search-bar__form">
        <div class="weui-search-bar__box">
          <i class="weui-icon-search"></i>
          <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="搜索" required="">
          <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
        </div>
        <label class="weui-search-bar__label" id="searchText">
          <i class="weui-icon-search"></i>
          <span>搜索</span>
        </label>
      </form>
        <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
    </div>
    <div class="weui-cells searchbar-result" id="searchResult" style="display: none;">
      <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
          <p>实时搜索文本</p>
        </div>
      </div>
      <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
          <p>实时搜索文本</p>
        </div>
      </div>
      <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
          <p>实时搜索文本</p>
        </div>
      </div>
      <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
          <p>实时搜索文本</p>
        </div>
      </div>
    </div>
    <div class="weui-media-box weui-media-box_small-appmsg">
      <div class="weui-cells">
        {% for member in members %}
        <a class="weui-cell weui-cell_access weui-cell_example" href="{% url 'family:modify_member' member.id %}">
          <div class="weui-cell__hd"><img src="{{ MEDIA_URL }}{{ member.image_path }}" alt="" style="width:20px;margin-right:16px;display:block"></div>
          <div class="weui-cell__bd weui-cell_primary">
            <p>{{member.first_name}}{{member.last_name}}</p>
          </div>
          <span class="weui-cell__ft"></span>
        </a>
        {% endfor %}
        <div class="weui-loadmore weui-loadmore_line">
            <span class="weui-loadmore__tips">暂无数据</span>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'libs/js/zepto.js' %}"></script>
<script type="text/javascript">
  $(function(){
    var $searchBar = $('#searchBar'),
      $searchResult = $('#searchResult'),
      $searchText = $('#searchText'),
      $searchInput = $('#searchInput'),
      $searchClear = $('#searchClear'),
      $searchCancel = $('#searchCancel');

    function hideSearchResult(){
      $searchResult.hide();
      $searchInput.val('');
    }
    function cancelSearch(){
      hideSearchResult();
      $searchBar.removeClass('weui-search-bar_focusing');
      $searchText.show();
    }

    $searchText.on('click', function(){
      $searchBar.addClass('weui-search-bar_focusing');
      $searchInput.focus();
    });
    $searchInput
      .on('blur', function () {
        if(!this.value.length) cancelSearch();
      })
      .on('input', function(){
        if(this.value.length) {
            $searchResult.show();
        } else {
            $searchResult.hide();
        }
      });
    $searchClear.on('click', function(){
      hideSearchResult();
      $searchInput.focus();
    });
    $searchCancel.on('click', function(){
      cancelSearch();
      $searchInput.blur();
    });
  });
</script>
{% endblock %}

family/templates/family/relationship_choose_family.html
{% extends "family/base.html" %}

{% block title %}选择家族{% endblock %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__bd">
    <div class="weui-cells__title">选择家族
       | <a href="{% url 'family:create_family' member.id %}">创建家族</a>
    </div>
    <div class="weui-cells weui-cells_form">
      <div class="weui-cell">
        <div class="weui-cell__hd"><label class="weui-label">成员姓名</label></div>
        <div class="weui-cell__bd">
          <input class="weui-input" type="text" value="{{member}}" disabled>
        </div>
      </div>
      <div class="weui-cell weui-cell_select weui-cell_select-after">
        <div class="weui-cell__hd">
          <label for="" class="weui-label">家族名称</label>
        </div>
        <div class="weui-cell__bd">
          <select class="weui-select" name="family_id">
            <option value="">请选择要关联的家族</option>
            {% for family in families %}
            <option value="{{family.id}}">{{family}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    </div>
    <div class="weui-btn-area">
      <a href="javascript:nextPage()" class="weui-btn weui-btn_block weui-btn_primary">下一步</a>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  function nextPage() {
    familyId = document.querySelector("select[name='family_id']").value
    if(familyId) {
      location.href =  "../joinFamily/" + familyId
    }    
  }
</script>
{% endblock %}